remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Brain Injury Knowledge Ontology for Traumatic Brain Injury (BIKO-TBI)]
description: [This site is documentation for the brain injury knowledge ontology for traumatic brain injury (BIKO-TBI)]
